### PR TITLE
Add raw links, add more affixes

### PR DESCRIPTION
**Pull request by ImaginaryDevelopment**

### CODE REVIEW

**Comment by poeaffix** [comment]
What are you using to edit?

**Comment by ImaginaryDevelopment** [comment]
I've got F# generating pages

**Comment by Sentracer** [comment]
The site is really messed up. I am removing you as a collaborate and am
reverting all your changes.

**Comment by ImaginaryDevelopment** [comment]
Well thanks for the detailed critique and warm wishes. I look forward to the updates.

**Pull request merged**
